"""Initial migration

Revision ID: 3ba625f6e930
Revises: 
Create Date: 2026-07-08 15:34:31.840380

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ba625f6e930'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_logs')
    with op.batch_alter_table('event_qr_codes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('guest_name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('rollno',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('mobile',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('qr_code',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('invite_sent',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('is_scanned',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.alter_column('device_ip',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('device_id',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('qr_code'))
        batch_op.create_index(batch_op.f('ix_event_qr_codes_qr_code'), ['qr_code'], unique=True)
        batch_op.drop_column('email_sent_at')
        batch_op.drop_column('created_by')
        batch_op.drop_column('email_status')
        batch_op.drop_column('updated_by')
        batch_op.drop_column('email_retry_count')
        batch_op.drop_column('last_email_error')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_qr_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_email_error', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('email_retry_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email_status', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email_sent_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_event_qr_codes_qr_code'))
        batch_op.create_index(batch_op.f('qr_code'), ['qr_code'], unique=True)
        batch_op.alter_column('device_id',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('device_ip',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('is_scanned',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('invite_sent',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.alter_column('qr_code',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('mobile',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('rollno',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('guest_name',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False,
               autoincrement=True)

    op.create_table('email_logs',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('guest_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('sent_at', mysql.DATETIME(), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('error_message', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['event_qr_codes.id'], name=op.f('email_logs_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
